server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/auth, /api/v1/users/**, /api/v1/users
          filters:
            - AuthenticationFilter
            - StripPrefix=2
        - id: access-control-service
          uri: lb://ACCESS-CONTROL-SERVICE
          predicates:
            - Path=/api/v1/roles/**, /api/v1/roles, /api/v1/permissions/**, /api/v1/permissions
          filters:
            - AuthenticationFilter
            - StripPrefix=2
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/notifications
          filters:
            - AuthenticationFilter
            - StripPrefix=2
        - id: property-service
          uri: lb://PROPERTY-SERVICE
          predicates:
            - Path=/api/v1/properties/**, /api/v1/properties, /api/v1/documents/**, /api/v1/documents
          filters:
            - AuthenticationFilter
            - StripPrefix=2
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/persons/**, /api/v1/persons, /api/v1/favoritos/**, /api/v1/favoritos
          filters:
            - AuthenticationFilter
            - StripPrefix=2
        - id: visit-calendar-service
          uri: lb://visit-calendar-service
          predicates:
            - Path=/api/v1/calendar/**, /api/v1/calendar, /api/v1/visits/**, /api/v1/visits, /api/v1/visit-requests/**, /api/v1/visit-requests, /api/v1/reassignments/**, /api/v1/reassignments
          filters:
            - AuthenticationFilter
            - StripPrefix=2
        - id: operation-service
          uri: lb://operation-service
          predicates:
            - Path=/api/v1/operations/**, /api/v1/operations
          filters:
            - AuthenticationFilter
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: ERROR
    "[com.inmobiliaria.api_gateway]": DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 1. Identity Service
        url: /identity-service/v3/api-docs
      - name: 2. User Service
        url: /user-service/v3/api-docs
      - name: 3. Property Service
        url: /property-service/v3/api-docs
      - name: 4. Access Control Service
        url: /access-control-service/v3/api-docs
      - name: 5. Notification Service
        url: /notification-service/v3/api-docs
      - name: 6. Visit Calendar Service
        url: /visit-calendar-service/v3/api-docs
      - name: 7. Operation Service
        url: /operation-service/v3/api-docs
