server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**,/users/**,/users
          filters:
            - AuthenticationFilter
        - id: access-control-service
          uri: lb://ACCESS-CONTROL-SERVICE
          predicates:
            - Path=/roles/**,/permissions/**,/roles,/permissions
          filters:
            - AuthenticationFilter
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - AuthenticationFilter
        - id: property-service
          uri: lb://PROPERTY-SERVICE
          predicates: 
            - Path=/properties/**,/properties,/documents/**,/documents
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/persons/**,/persons,/audit-logs/**,/audit-logs
          filters:
            - AuthenticationFilter
        - id: visit-calendar-service
          uri: lb://visit-calendar-service
          predicates:
            - Path=/api/calendar/**, /api/visits/**, /api/visit-requests/**
          filters:
            - StripPrefix=0
        - id: favorites-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/favoritos/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: ERROR
    '[com.inmobiliaria.api_gateway]': DEBUG