server:
  port: 8082

spring:
  application:
    name: access-control-service

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/inmobiliaria_db?authSource=admin

  cache:
    type: caffeine

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true
  instance:
    hostname: localhost
    prefer-ip-address: true