server:
  port: 8086

spring:
  application:
    name: visit-calendar-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/inmobiliaria_db?authSource=admin
  cloud:
    config:
      enabled: false  # Desactiva la búsqueda del Config Server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true
  instance:
    hostname: localhost
    prefer-ip-address: true